sudo: required
dist: xenial
language: python
python:
  - "3.7"
  - "3.6"

install:
  - make install
  - pip install coveralls

script:
  - make release-check

after_success:
  - coveralls

deploy:
  provider: pypi
  user: blindspot-ai
  password:
    # master
    # secure: "p324XIUL4vrCoDuTRjt6uyHztciwatmJktsNljjDVKceM1BNGX1RAc8EhXNSpgLqBfETAqVujzVeeg1wPMMcfHypBQGjNoJoc9WQaGms5khqqqYGvJtU1FSjteBWIKDMFQtL5t2wjSnGw8GsOfsEz+whcbaFdEAknrX+W1pPunFadboesiV0PFToVwuLfn266uGOGDFGvzp3QtKFzG0eWlEj4a3nHDOBgMJddIzYOQ689Kr9qiBbsn1m9vcfUZ/G7xkEEtp2J0R8Ug8B3hkeItSHShT2OJdkx9cCdBkhOmniUsDTjUzBw4P1DPB1dtuf2p0QjNq8jW42sx6CZpxX5+AyFwgh3K0UYArcYKfvmSXYMVpOUavtI5rczySCiSfC708gmKnYatBQgpfa2tg+07re5GK7DiKAtOOYGNl7yQHWtPAOGd1JcI0p4qc27WKJyrc56SQNnIw5Sa1R9PUkxsd2UHXguCxN/UaOYRoH7Se/VqhSD6s4p2Jt2wI+dRNs8LW50KotdjbutHCoEwsw5R0Qt5yX7Caq965EZgauNrsqHidZcc9mJau+E6qVShbKCrDLhgRc+ALtaEPRQwL/C3ZanuZBX8LJweA7QW+s0G+mq85U/5ixqrnCfZmZaav+B5OUeXxckJxlkpZWWFPe/Vggh3t4Tw9m7jp7A2AQisg="
    # test
    secure: "ZZVuRbmRPChcSJbOk9i6QUIXIeXv96DKCDUw90s04Ea2iuOz4yDTizJevNW7gz+AQtECfUVAMqNi2bt2QJ179PQzi2AptcvgpxXz1pTTziIwdv4uaZANDO5qt4s2uApUkKFAa15ovMoODtTPLhMVtVxEJww32YEZ/O7/jVW3P6V+PRVmdCaWf5ZvlSe2XGkV+Ydj4NDp9/c+bVjAZC9AOJefw0zTEMWKEeuqHOS7Qq6ocGqmTTRIvtcWOiInZQKnfLjelPlrKEgeQZAv4qKyfv9S4pkDaIRLTNUaPVBGhYTZPojxdUGwORKUxkBeqY5es8vs34eu48w4NEgKCfnm1MB1zdQcl1KBd6oyFAufpw3JqN4e8pyjaNeQuwPH5fCFvPZLEgEJq9nMTpdxRLU8gp7SfgYDZP2JYBQsLvAD5h//+HNCmiiqIkTXc/p1PwUFwh/wyj5mDJO0rHeb13xLMyHUbMN9VyYfCA9lbaBT6LRJcdNOZgMAv81piRckXyBImXPm4Yk3xdCPbo+BhVvAXIroPL2qDkXuOfiCVUlc/5qnezyYbnDnyXDS9vJckpA87TBspktiiT6Ylt4JRwn09ubV7NTq6H+XQcuUTFqqAMeJ22kq8v/XNsYXaR4bofgnlJI3/BLatasWytFaSoqxjVT0jjSw0YXJX3lu+dWh7MY="
  distributions: sdist
  skip_cleanup: true
  server: https://test.pypi.org/legacy/
  on:
    # branch: master
    branch: configure-bumpversion
    tags: true
    python: 3.6
    skip_existing: true
