sudo: required
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

install:
  - make install

script:
  - make release-check

after_success:
  - pip install coveralls --use-mirrors
  - coveralls
