sudo: required
dist: xenial
language: python
python:
  - "3.7"
  - "3.6"

install:
  - make install
  - pip install coveralls

script:
  - make release-check

after_success:
  - coveralls

deploy:
  provider: pypi
  user: blindspot-ai
  password:
    # master
    # secure: "ceNrUixiWTM5/5O3YIMo4XtZtJ6Nc+FuCc8CCHI7OXSn9/xzrkRELsJx8nb24gpdPtAxj3L7T/P4iGkbe47I+a+OOqpA/R5LEg1TWlYLpfhEllSbtxHgpkF6uETqH6sJ3RHAIGziTtFvGZzVEWdOnP1lU6WyjfV5/LU1g6tK6Xmf/uZEcie9z2aYqz9nIXRZkz0EFClKOwvZ/ZvgdU2Ho0jOW6jwDh+LJEb1UmO9BDvLvmSk0qgH5/SJtYXZZ6RhQw0Xxa+pPqZAu/P4z03ov8FXijIjXu3tjG+chwQ6oYJbDO0gX+nslcmvKgl54x4WUu2hFfLN2ZjupevrnPW2AtY6F68mu12Jq2VZdgB/U1xRf4RDTF2RmcQ5uXtieMHszrGJ9pFeNfjRco4nMOpAfKRgt88jX06Q/oVWzQt10xuSuvqQaQI6sv06NLyv9Jn7BVj1VZJiK4eb+WV//KSdW5OvJnBwqvnL1sT61IqcQgP7me631zkUu4IR3gzloJ2g1JEAEZ/Jr1NO6dPyqdvv8rnlJwHRoM/0SiInPbkoOxu88AYPfAdzoYtEle8Bpu7FDlGQRnuislzYqEGFHAmK4Ghq5ITCaoXg+TEW1+8Bu5xfQSobtrLlzVX2l261nxZoX3hAPm9nkztBPmEOXgeslqHr0fOP2FC9QQfaWQitaOI="
    # test
    secure: "ZU4ohYhDP3VpMzGmF+IrZX0/kXK6r2njjlpMDB7NRYaGLakMuEqusSeZkEeYwOOYujsH7RCyi/0tDDchVg25V8HwG3Quh/r5gDo6e9Jw/o5zdm1b8gynK15JgdTh5vAdLnatKPFfZ6J+5dDog0MLaIXpCF4Zxx24FXNRp0BlBnZuHwT9EjjhN0mcT0v2m6ErXJ4VQGRXkRomWnp0z1ifiMCshWJ/ZQEBpI8A88k3HqPDi0uFzWnGl/uqZs3JY2D2XK4AYRGzhtyPoM/E/SN/pYmYKC108+uvqz/MIFCV9IhIpTomPG0qQ9rqMA+k4gUkMkKtRO2Q0OcHHMQXY6X73u65ka1Z3+3+Gc6ROyyjqCb3Q5EvNB9ax81USn9ImKRiv7pfx/WHsYQap7ctZ6Kygn3MjLZGCiDmeIs5tLAXZkCF3k1Zkn8SLm4m23FmUB7UmoKtV6TqhcmFo9FCq8PV5YTpbRjzBtYiL2qzKZkOcNdC88MF1uZ2L55Sp/h5wz64XewT+ZmKjHm1pKBR/WxRPEpszm6f0OHQmZfTChexQ+V43lj5pWcP0jvIDW50chzttjjh23ZVHnAAoUCZ0YHPJIc7WQR3iGPBlQji7vNc4+9hiAtV2az206tY9wkpLMjR1b2SykbPYPbtIqMFvnCgTA04ckmVubOMlsg2js1q2f8="
  distributions: sdist
  skip_cleanup: true
  on:
    # branch: master
    branch: configure-bumpversion
    server: https://testpypi.python.org/pypi
    # tags: true
    python: 3.6
    skip_existing: true
