sudo: required
dist: xenial
language: python
python:
  - "3.7"
  - "3.6"

install:
  - make install
  - pip install coveralls

script:
  - make release-check

after_success:
  - coveralls

deploy:
  provider: pypi
  user: blindspot-ai
  password:
    # master
    # secure: ceNrUixiWTM5/5O3YIMo4XtZtJ6Nc+FuCc8CCHI7OXSn9/xzrkRELsJx8nb24gpdPtAxj3L7T/P4iGkbe47I+a+OOqpA/R5LEg1TWlYLpfhEllSbtxHgpkF6uETqH6sJ3RHAIGziTtFvGZzVEWdOnP1lU6WyjfV5/LU1g6tK6Xmf/uZEcie9z2aYqz9nIXRZkz0EFClKOwvZ/ZvgdU2Ho0jOW6jwDh+LJEb1UmO9BDvLvmSk0qgH5/SJtYXZZ6RhQw0Xxa+pPqZAu/P4z03ov8FXijIjXu3tjG+chwQ6oYJbDO0gX+nslcmvKgl54x4WUu2hFfLN2ZjupevrnPW2AtY6F68mu12Jq2VZdgB/U1xRf4RDTF2RmcQ5uXtieMHszrGJ9pFeNfjRco4nMOpAfKRgt88jX06Q/oVWzQt10xuSuvqQaQI6sv06NLyv9Jn7BVj1VZJiK4eb+WV//KSdW5OvJnBwqvnL1sT61IqcQgP7me631zkUu4IR3gzloJ2g1JEAEZ/Jr1NO6dPyqdvv8rnlJwHRoM/0SiInPbkoOxu88AYPfAdzoYtEle8Bpu7FDlGQRnuislzYqEGFHAmK4Ghq5ITCaoXg+TEW1+8Bu5xfQSobtrLlzVX2l261nxZoX3hAPm9nkztBPmEOXgeslqHr0fOP2FC9QQfaWQitaOI=
    # test
    secure: eXdTBxdl4Ro4mgpNhbt/FxooQbvq0omLTJe4yjGqUCX8qSn8k/JkaJjvyMVgU0ZFvzm35cUCYj/oGlRepToVJYZalBI4/O3kZsnRnADwecKrjycLQs8MOCWhX4ZOExpuHHr+XieYvLw50HsIt09x/g0iEMmwR+OgW/d3pdoVpKitnkPoL65hoSZVps7SzbbhIEO8qbYOESLXHLGtqS98kpBEld89Lj0W9NPqaH2Gzpzrq9GBTWfywhzLvkMeEDhoxwecIBTRl3iVvcf6sF2q2k6KdrwTtDikxfCH+psKR1MIKOuB3vCGQAKPjmYDqAC8vonrAvJYIU1DHGIVQq15qDbpTBiyw/YUTgE+3TcFazx7VCt1pXNrMcU7Ayif5deKnKJ5bC8iu472DurCQ2a6TZOkRGJfM+ysTS94JdU+Ng5R4Bd1aDU1fh4VVGjsnJrs7ziXRWHLNLniGkarkl/v1/5xbIjGT6ZQj8fSnKZEOynAkKPiQMDN+WMnKcGdCVmuKhe6ZIsurb/If0Ozff/syvnxYj6ZSI0Ey8lOLYZ/sK569lE9U9jVv6AOaij+OYYmWCJRWmO9c/yepSuOuoSflyEyTGxg8RSL7PdCZEga1qcrFLyokj3DU4ReqC6g6N3YC/B2QS1AURgzqUgAY3ydHaLaFY9jsYEaJmkoCW9XCaM=
  distributions: sdist
  skip_cleanup: true
  on:
    # branch: master
    branch: configure-bumpversion
    server: https://test.pypi.org/legacy/
    tags: true
    python: 3.6
    skip_existing: true
